version: "2.1"

x-common: &common
  environment:
    - DEBUG=True

services:
  backend:
    <<: *common
    container_name: demo_backend
    build:
      context: ./backend
    ports:
      - "5000:5000"

  orders:
    <<: *common
    container_name: demo_orders
    build:
      context: ./orders
    ports:
      - "5001:5000"

  items:
    <<: *common
    container_name: demo_items
    build:
      context: ./items
    ports:
      - "5002:5000"